# Deployment Target
platform :ios, '8.0'

# Add pods as frameworks so we could add obj-c and swift 3.0 pods
use_frameworks!


target 'StretchScrollView_Example' do
    pod 'APExtensions'
    pod 'StretchScrollView', :path => '../'

    target 'StretchScrollView_Tests' do
        inherit! :search_paths

        pod 'Quick'
        pod 'Nimble'
        pod 'FBSnapshotTestCase'
        pod 'Nimble-Snapshots'
    end
end
