# Deployment Target
platform :ios, '8.0'

# Add pods as frameworks so we could add obj-c and swift 3.0 pods
use_frameworks!

# Cartage support
install! 'cocoapods',
    :share_schemes_for_development_pods => true


target 'StretchScrollView_Example' do
    pod 'APExtensions'
    pod 'BaseClasses'
    pod 'StretchScrollView', :path => '../'

    target 'StretchScrollView_Tests' do
        inherit! :search_paths

        pod 'Quick'
        pod 'Nimble'
        pod 'FBSnapshotTestCase'
        pod 'Nimble-Snapshots'
    end
end


post_install do |installer|
    # Carthage support.
    # It puts `StretchScrollView.swift` into public headers so @IBInspectable won't be stripped out.
    additionHeader = installer.pods_project.development_pods['StretchScrollView/StretchScrollView.swift']
    headersBuildPhase = installer.pods_project.targets.select{ |x| x.name == 'StretchScrollView' }[0].headers_build_phase
    buildFile = headersBuildPhase.add_file_reference(additionHeader)
    buildFile.settings = { 'ATTRIBUTES' => ['Public']}
end
