# Deployment Target
platform :ios, '9.0'

# Add pods as frameworks so we could add obj-c and swift 3.0 pods
use_frameworks!


target 'StretchScrollView_Example' do
  pod 'APExtensions', :git => 'https://github.com/APUtils/APExtensions'
  pod 'BaseClasses', :git => 'https://github.com/APUtils/BaseClasses'
  pod 'StretchScrollView', :path => '../'
  
  target 'StretchScrollView_Tests' do
    inherit! :search_paths
    
    pod 'Quick'
    pod 'Nimble'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end


post_install do |installer|
  # Add podInstall.command and podUpdate.command shell scripts to Pods project
  pods_project = installer.pods_project
  pods_project.new_file "../Scripts/Cocoapods/podInstall.command"
  pods_project.new_file "../Scripts/Cocoapods/podUpdate.command"
  
  # Silence Pods project warning
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED'] = 'YES'
  end
  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
