# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.3
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/StretchScrollView.xcworkspace -scheme StretchScrollView-Example -destination "platform=iOS Simulator,id=B9ADB233-F32D-433C-B53B-5D21132BE7B6" ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
- pod spec lint
