# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.3

language: objective-c

cache:
    directories:
     - Carthage
     - Example/Pods
     
podfile: Example/Podfile

before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update
- pod install --project-directory=Example
- brew install carthage
- carthage bootstrap --platform iOS --cache-builds

script:
- bash checkBuild.command
- pod lib lint
- pod spec lint
